
global:

  loglevel: INFO

  docker:
    repo: 513562861795.dkr.ecr.us-west-2.amazonaws.com

  domain:
    name: labber.io

  gfsnamespace: namespace

  gfsapi:
    hostname: labber-gfsapi
    port: 5000
    username: root
    password: root

  rabbitmq:
    hostname: labber-rabbit
    port: 5672
    username: rabbitmq
    password: rabbitmq


gfspulsinator:

  image:
    repository: gfs-pulsinator
    tag: latest
    pullPolicy: Always


gfspusher:

  image:
    repository: gfs-pusher
    tag: latest
    pullPolicy: Always


gfsrenderer:

  image:
    repository: gfs-renderer
    tag: latest
    pullPolicy: Always


gfsrippler:

  image:
    repository: gfs-rippler
    tag: latest
    pullPolicy: Always


gfssubscriber:

  image:
    repository: gfs-subscriber
    tag: latest
    pullPolicy: Always
